language: python
services:
  - docker
python:
  - 2.7
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial
install:
  - pip freeze
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip freeze
script:
  - pylint chmod_monkey
  - coverage run --source=chmod_monkey -m pytest
  - python setup.py build
after_success:
  - coveralls